language: go

go:
  - 1.2
  - 1.3

install: 
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/coreos/etcd
  - bad=$(gofmt -s -l pkg/ cmd/) bash -x -c '[[ -z "$bad" ]]'
  - ./hack/verify-boilerplate.sh
  - ./hack/build-go.sh

script:
  - ./hack/test-go.sh
  - PATH=$HOME/gopath/bin:$PATH ./hack/integration-test.sh

notifications:
  irc: "chat.freenode.net#google-containers"
